function p = plotter(r,del,p)

	% This function handles all the plotting (except for figure titles)

	% If i>1 then del == 1, and we delete the last plots from the figure, so it
	% looks like an animation
	if del == 1
		delete(p.r1);
		delete(p.r2);
		delete(p.r3);
		delete(p.r4);
		delete(p.r5);
		delete(p.r6);
	end

	% Next we do the 6 scatter plots. One for each state. put them in the p
	% struct
	p.r1 = scatter(r.pos(1,r.race == 1),r.pos(2,r.race == 1),...
					'LineWidth',r.dot_size,...
					'Marker','o',...
					'DisplayName','R1 base',...
					'MarkerFaceColor', r.col(1),...
					'MarkerEdgeColor', r.col(1));
	p.r2 = scatter(r.pos(1,r.race == 2),r.pos(2,r.race == 2),...
					'LineWidth',r.dot_size,...
					'Marker','o',...
					'DisplayName','R2 base',...
					'MarkerFaceColor', r.col(2),...
					'MarkerEdgeColor', r.col(2));
	p.r3 = scatter(r.pos(1,r.race == 3),r.pos(2,r.race == 3),...
					'LineWidth',r.dot_size,...
					'Marker','o',...
					'DisplayName','R1 panic',...
					'MarkerFaceColor', r.col(3),...
					'MarkerEdgeColor', r.col(3));
	p.r4 = scatter(r.pos(1,r.race == 4),r.pos(2,r.race == 4),...
					'LineWidth',r.dot_size,...
					'Marker','o',...
					'DisplayName','R1 panic 2',...
					'MarkerFaceColor', r.col(4),...
					'MarkerEdgeColor', r.col(4));
	p.r5 = scatter(r.pos(1,r.race == 5),r.pos(2,r.race == 5),...
					'LineWidth',r.dot_size,...
					'Marker','o',...
					'DisplayName','R1 sick',...
					'MarkerFaceColor', r.col(5),...
					'MarkerEdgeColor', r.col(5));
	p.r6 = scatter(r.pos(1,r.race == 6),r.pos(2,r.race == 6),...
					'LineWidth',r.dot_size,...
					'Marker','o',...
					'DisplayName','R2 hunting',...
					'MarkerFaceColor', r.col(6),...
					'MarkerEdgeColor', r.col(6));
	% If i == 1 then del ~=1 and it's the first plot. Then we set the axis and
	% add a legend.
	if del ~= 1
		legend('location','eastoutside')
		axis([0 r.side 0 r.side])
	end
	drawnow
end